"""empty message

Revision ID: 46bbab07eb28
Revises: 2221e1daca11
Create Date: 2019-08-31 16:19:52.746824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bbab07eb28'
down_revision = '2221e1daca11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('agenda_slug', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'contact', ['agenda_slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.drop_column('contact', 'agenda_slug')
    # ### end Alembic commands ###
