"""empty message

Revision ID: 4c54ffc4ae40
Revises: 46bbab07eb28
Create Date: 2019-09-03 21:25:58.154475

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c54ffc4ae40'
down_revision = '46bbab07eb28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contact', 'address',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('contact', 'phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.drop_index('agenda_slug', table_name='contact')
    op.drop_column('contact', 'agenda_slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('agenda_slug', mysql.VARCHAR(length=120), nullable=False))
    op.create_index('agenda_slug', 'contact', ['agenda_slug'], unique=True)
    op.alter_column('contact', 'phone',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('contact', 'address',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
