"""empty message

Revision ID: b6bdb61fcd48
Revises: 4c54ffc4ae40
Create Date: 2019-09-03 22:12:59.655074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6bdb61fcd48'
down_revision = '4c54ffc4ae40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('address', table_name='contact')
    op.drop_index('full_name', table_name='contact')
    op.drop_index('phone', table_name='contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('phone', 'contact', ['phone'], unique=True)
    op.create_index('full_name', 'contact', ['full_name'], unique=True)
    op.create_index('address', 'contact', ['address'], unique=True)
    # ### end Alembic commands ###
